import { FIRST_PROJECT_CONTENT_RUS } from '~/helpers/content/code-examples/1.content';

export const CODE_EXAMPLES_RUS = [
  FIRST_PROJECT_CONTENT_RUS,
  FIRST_PROJECT_CONTENT_RUS,
  FIRST_PROJECT_CONTENT_RUS,
  FIRST_PROJECT_CONTENT_RUS,
];
